// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVrM7kADDseZoqtPcIrnEQVtrRiavSlhs',
    appId: '1:714127777029:web:c5d01c3c4f66db7b57ab6c',
    messagingSenderId: '714127777029',
    projectId: 'caleb-choir-2026',
    authDomain: 'caleb-choir-2026.firebaseapp.com',
    storageBucket: 'caleb-choir-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBktXCxzhGx0FODnm-mdHveXhe7rFK6Rts',
    appId: '1:714127777029:android:368bc1b07d147d2557ab6c',
    messagingSenderId: '714127777029',
    projectId: 'caleb-choir-2026',
    storageBucket: 'caleb-choir-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbqvK7XJ2Nv4o4Lh3p71zPg0jvfhSB9-M',
    appId: '1:714127777029:ios:842902ac3abded7457ab6c',
    messagingSenderId: '714127777029',
    projectId: 'caleb-choir-2026',
    storageBucket: 'caleb-choir-2026.firebasestorage.app',
    iosClientId: '714127777029-ujl5cr93mn5q4j9371k3h1kgdflu1c6p.apps.googleusercontent.com',
    iosBundleId: 'com.calebchoir.calebChoir',
  );

}